# docker-compose.yml (개발 Docker)

version: '3'
services:
  pinup_db:
    container_name: pinup_db
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: pinup
      MARIADB_ROOT_PASSWORD: QGWGPnEGBW8Ss1Dm3I7o
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pinup_net

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pinup_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinup
    depends_on:
      - pinup_db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://pinup_db:3306/pinup?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: QGWGPnEGBW8Ss1Dm3I7o
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - pinup_net

networks:
  pinup_net: { }

volumes:
  mariadb_data:
  redis_data: