services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinup
    ports:
      - "8080:8080"
    networks:
      - pinup_net
  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "6565:6565"
    volumes:
      - ./src/main/resources/script.js:/script.js
    command: run /script.js
    network_mode: host
    depends_on:
      - app

networks:
  pinup_net: {}