version: '3'
services:
  spring:
    container_name: pinup-was
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://pinup_db:3306/pinup?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mariadb
      - redis
      - prometheus
      - grafana
    networks:
      - pinup_net

  mariadb:
    container_name: pinup_db
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: pinup
      MARIADB_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pinup_net

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pinup_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - pinup_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    privileged: true
    networks:
      - pinup_net

  k6:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./src/main/resources/script.js:/script.js
    command: run /script.js
    network_mode: host
    depends_on:
      - spring

volumes:
  mariadb_data:
  redis_data:

networks:
  pinup_net: {}