spring:
  config:
    import: application-secret.yml
  profiles:
    default: local
    group:
      local:
        - application-secret
      dev:
        - application-secret
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      default_batch_fetch_size: 500
    open-in-view: false
  cache:
    type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  devtools:
    livereload:
      enabled: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
  error:
    whitelabel:
      enabled: false

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
