server:
  port: 8080
  # 웹 애플리케이션을 구분할 때 사용
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
  # 예외 처리를 커스텀하게 진행하기 위해 Whitelabel Error Page 옵션 OFF
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # 콘솔창에 출력되는 SQL문을 사람이 보기 편한 형태로 출력
        default_batch_fetch_size: 500 # 1:N 컬렉션 조회 시 성능 최적화
        highlight_sql: true
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
  cache:
    type: redis

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 출력되는 SQL문에 ?가 아닌 조건에 바인딩 되는 값 및 조회 결과 출력
    org.hibernate.SQL: debug
    com.pinup: debug

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus