spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/pinup?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${IP_DEV}:29092, ${IP_DEV}:39092, ${IP_DEV}:49092

kakao:
  key: ${MAP_KAKAO_KEY}

oauth2:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
