kakao:
  key: ENC(see5tyJL6AFik2R4ee4c5HGXIjC7vAwMxaMDygzWR987u3sXkrBovDqsbWHHDh/I)

cloud:
  aws:
    credentials:
      access-key: ENC(AnksJZP1Xn0VxeDpe3HJvFmBUP0rxA3TwuaAXnVI3Yk=)
      secret-key: ENC(Qk2i3Cl/shbu2G1cG/pHoipqR1qFTz+sVoOoLD/BKTkY+bZ+/lhDvT72FwQuNzskslMRNtEQqXk=)
    s3:
      bucket: pinup-bucket-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false

oauth2:
  google:
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v3/userinfo
    auth-uri: https://accounts.google.com/o/oauth2/auth
    client-id: ENC(qd198+AFgz4L59h6n0tfE+t4AerWO11/9qm3KeiwLJDJdEAg+ovCyn7ep5xE3XaLvsCZ/a2rpuxvIaM0KtE9yHx+lkrwpPNl6n8Nbh8RqDw9MJXQjFiOCg==)
    client-secret: ENC(jRizQ/Tdov9REdRhf2w9+yyz5xoE6+UzdhZzG5jfztx0WQZGvtAds7m9Eotz2KoQ)
    redirect-uri: postmessage

jwt:
  access-token-validity-in-seconds: 21600 # 6시간 (60 * 60 * 6)
  refresh-token-validity-in-seconds: 604800 # 7일 (60 * 60 * 24 * 7)
  secret: ENC(YqTiMCthuQiZAMhevppJtfUX2TDLbyaFyZF4T+7Mj+VeBTLTFPF6qat0Ek2UK2DPfJoxSdkVaVvCWUcX8GmRJUW9BjwBgYEPNeVnoYshCj6e0tx0WwNIhdlqImJFlBcw+C5XHV5tF+qt+qwULHNAV6eiAWWlH/6L)
